name: 'ci-nodejs-package'
description: 'Package the artifact'

inputs:
  working-dir:
    description: 'the project working directory'
    required: true
  packager:
    description: 'zip or tar package manager to use'
    required: false
    default: 'tar'
  assets:
    description: 'list of files or folders that you wanted to be included as the artifact. seperated by ","'
    required: true

outputs:
  is_updated:
    description: 'informs if the update was done successfully or not'

runs:
  using: node16
  main: dist/index.js

branding:
  color: 'blue'
  icon: 'archive'